/*@create-file:build.opt@

-DUMM_INIT_USE_ICACHE=1

-DDEBUG_FLASH_QE=1


// Use these to disable options, default to enable, 1.
// -DBUILTIN_SUPPORT_GIGADEVICE=0
// -DBUILTIN_SUPPORT_MYSTERY_VENDOR_D8=0
// -DBUILTIN_SUPPORT_SPI_FLASH__S6_QE_WPDIS=0
// -DBUILTIN_SUPPORT_SPI_FLASH_VENDOR_EON=0

*/
